### ISSUE TITLE
Performance on Android

### ISSUE THREAD

**Issue by stoff99** [devsmadeofsteel/Plugin.HybridWebView#2]
Hello @candidodmv ,

firstly thx for your fork, nice work.

We use this in our Xamarin Forms project.
I have a question related to the Android performance.
I figured out that the performance on Android is much lower than on iOS.

Are there some tips or tricks to improve the performance on Android side?
Maybe with a customer renderer or something like that?

Thx Stefan

**Comment by candidodmv** [comment]
You're welcome! I keep happy know that this effort was useful for someone.
But what kind of performance are you referring? What is the scenario you are facing issues?

**Comment by stoff99** [comment]
Hi, 
the problem we see is that the loading performance of the exact same page takes much longer on Android than on iOS.
I recored your a video related to that: https://www.dropbox.com/s/tgqw9plhuft7j6a/WebView_iOS_vs_Android.mov?dl=0

**Comment by stoff99** [comment]
I wrote a lot of enable android:hardwareAccelerated="true" for the Webview renderer but i dont get this to work with your library.
Like that:
`
[assembly: ExportRenderer(typeof(WebView), typeof(CustomWebViewRenderer))]
namespace XXX.Droid.Renderers
{
    public class CustomWebViewRenderer : WebViewRenderer
    {
        public CustomWebViewRenderer(Context context) : base(context) { }
 
        protected override void OnElementChanged(ElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
 
            if (Control != null)
            {
                if ((int)Build.VERSION.SdkInt >= 19)
                {
                    Control.SetLayerType(Android.Views.LayerType.Hardware, null);
                }
                else
                {
                    Control.SetLayerType(Android.Views.LayerType.Software, null);
                }
            }
        }
    }
}
 `

But when i replace the WebView with your HypridWebView i get errors because of the wrong type.

**Comment by candidodmv** [comment]
Hello @stoff99 , now I could understand what you are referring to. Well, let's began from begin ...

The performance problems are more complex than you can imagine, due may there are to many reasons that can turing the any operation slower .

Such as:

- Hardware limited
- [differences of S.O implementations](https://www.quora.com/Why-is-Android-so-slow-when-compared-to-iOS)

In case of WebView we can cite some additions

- Network latency
- Web page heavy

But, what I found as suggestion [on the web](https://stackoverflow.com/questions/7422427/android-webview-slow), [and here](https://stackoverflow.com/questions/32304237/android-webview-loading-data-performance-very-slow), is really what your code snippet suggest above, what we can do, is try to implement this code and see if there any improvements, what do you think?

I will put this changes in a preview release version, you checkout if get better and give me the feedback related about.

**Comment by stoff99** [comment]
Hello @candidodmv 

yes i know ;)
We was testing a lot the last days. We found also issues on server side.
We minimize a lot of js files and stuff like that.
We had also issues with the caching system. So the server returned status code 200 instead of 304 so the webview loads the files again and did not restore out of the cache and stuff like that ... :)

So if you could do that, that would be great!
Please tell me when you release this version and we will test if there is a difference!

Thx a lot for your time and help.
Greetings from austria!

**Comment by stoff99** [comment]
Hello @candidodmv ,

thx for this good news.
We will test them as fast as possible and let you know.

**Comment by stoff99** [comment]
Hello @candidodmv ,

i had time right now to check.
The render time feels faster now. But its always hard to measure.
We will test while developing.

Thx a lot for your support.

**Comment by candidodmv** [comment]
You're welcome @stoff99 , any news about the peformance please register here!
