### ISSUE TITLE
Call JS Function from C#

### ISSUE THREAD

**Issue by BlackZero1122** [devsmadeofsteel/Plugin.HybridWebView#27]
Hello @candidodmv,

I know we can call C# code from js using this library. Is there a way to call JS Function from C#?

**Comment by candidodmv** [comment]
Hello @BlackZero1122!
Yeah, you can do by call [Task<string> InjectJavascriptAsync(string js);](https://github.com/devsmadeofsteel/Plugin.HybridWebView/blob/6f08a796b7d90bc84eee716a9dfc90afc095a360/HybridWebView/Shared/IHybridWebView.cs#L44) .

You provide your javascript function(body or signature, already existing within the page) and await for the response.
Tip. If the return is object you must serialize as json in javascript side and deserialize in c# side.

Hope it helps!

**Comment by BlackZero1122** [comment]
Thank you sir, will try that.
