### ISSUE TITLE
[Xamarin.iOS] Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by stoff99** [devsmadeofsteel/Plugin.HybridWebView#3]
Hello @candidodmv ,

Apple flaged the use of UIWebview as deprecated some time ago. You will get this warning when you upload the build to the Apple Store.

There is now already a prerelease of Forms where this is refactored to WKWebView: https://github.com/xamarin/Xamarin.Forms/issues/7323

This will effect also this library in near future when apple let us not upload new apps on the 04.2020 and blocks also app updates after 12.2020.
My question is now if you plan to refactor also this library to be working again when the official stable Forms release is available?

Thx Stefan

**Comment by candidodmv** [comment]
Hi @stoff99 this plugin aready is using WKWebView on iOS implmentation as you can see in the following line:
https://github.com/devsmadeofsteel/Plugin.HybridWebView/blob/f0d2915dea8d1d0befb4a13b1836b2ff6dc5d34d/HybridWebView/iOS/HybridWebViewRenderer.cs#L21

As you cited above the incompatibility was targeting WebView control of XF  implementation. Do you have used the preview version of XF update that fix this problem and are stilll appearing this warning on Apple Store ?

**Comment by stoff99** [comment]
Hi @candidodmv ,
thx for your replay. 
Thats perfect!
No i didn't test the upload right now. I'm sure its working. I just want to make sure that we don't run into a problem in the near future.

Thx again!
