### ISSUE TITLE
Is there a way to open a server pdf file

### ISSUE THREAD

**Issue by jrthurler** [devsmadeofsteel/Plugin.HybridWebView#7]
I'm trying to open a remote address with a pdf file, instead of a page.
Is there a way to show the pdf contents from a server file?

**Comment by candidodmv** [comment]
Hello, there are two ways to accomplish this:

1) Using PDF.js as described in the [following reciped](https://github.com/xamarin/docs-archive/tree/master/Recipes/xamarin-forms/Controls/display-pdf)
2) Using a native control to renderer PDF such as [Syncfusion PDF Viewer](https://devblogs.microsoft.com/xamarin/xamarin-forms-apps-syncfusion-pdf-viewer/) (tip: there's available a community license version)
