### ISSUE TITLE
Android: NullReferenceException when returning form far away tab 

### ISSUE THREAD

**Issue by gerricom** [devsmadeofsteel/Plugin.HybridWebView#8]
Steps to reproduce:

1. Create a Xamarin.Forms app with a TabbedPage as MainPage.
2. Create 5 tabs
3. Place the HybridWebView on the first tab with StringData as source
4. Start the app on Android. Navigate to the fifth tab and back to the first
5. get following exception:

> Object reference not set to an instance of an object.
>   at Plugin.HybridWebView.Droid.HybridWebViewRenderer+<>c__DisplayClass34_0.<SetCurrentUrl>b__0 () [0x00016] in <c65042315c674147a4dba4db994cc7fb>:0 
>   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <55654ebe9f2a48e6bade2862bb243f94>:0 
>   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <55654ebe9f2a48e6bade2862bb243f94>:0 
>   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.1(intptr,intptr)

I guess this is because Android disposes my WebView when I'm far away from the first tab. [Then this function](https://github.com/devsmadeofsteel/Plugin.HybridWebView/blob/5e8613dd1f500df599545e02db624cf81399f5fa/HybridWebView/Droid/HybridWebViewRenderer.cs#L452) is called and because I don't have an URI it throws the exception. 
But it's just a guess as I had not the time yet to test it with your sample code.

**Comment by gerricom** [comment]
[I added a PR](https://github.com/devsmadeofsteel/Plugin.HybridWebView/pull/9) that fixes this issue and provides a simple test page.

**Comment by stoff99** [comment]
Nice thx @gerricom ,
Today i got the same error as you. I checked out the project and tried it. It fixed also the problem on my side.
Could anybody create a NuGet update with this fix?
